refactor!: Preparation for v2 release
apify/apify-sdk-python pull request #210
Opened 2024-06-04 20:26 UTC by janbuchar

- **Update pyproject.toml**
- **Use storage code from crawlee, add ApifyStorageClient**

- [x] make sure we use `APIFY_IS_AT_HOME` instead of token for all platform vs. local decisions
- [x] port over `warnedAboutMissingInitCall` from JS SDK (this is not exactly ported over, but we expect this won't happen frequently, so we just throw an exception)

### Issues

- Closes: #135
- Closes: #137
- Closes: #138
- Closes: #147
- Closes: #149
- Closes: #237

2024-08-22 13:16 UTC, janbuchar commented on src/apify/storages/__init__.py
add __all__ instead of re-exports

2024-08-22 15:45 UTC, vdusek requested changes
Great job :pray:.

Sending a few comments...

2024-08-22 15:45 UTC, vdusek commented on pyproject.toml
>  [project]
Regarding the imports sorting, I'd add either:

```toml
[tool.ruff.lint.isort]
known-first-party = ["apify"]
```

or even include all our pckgs:
```toml
[tool.ruff.lint.isort]
known-first-party = ["apify", "apify_client", "apify_shared", "crawlee]
```

to distinguish from 3rd party pckgs.

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/dataset_client.py
> +from crawlee.base_storage_client.base_dataset_client import BaseDatasetClient
```suggestion
from crawlee.base_storage_client import BaseDatasetClient
```

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/apify_storage_client.py
> +from crawlee.base_storage_client.base_storage_client import BaseStorageClient
```suggestion
from crawlee.base_storage_client import BaseStorageClient
```

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/dataset_collection_client.py
> +from crawlee.base_storage_client.base_dataset_collection_client import BaseDatasetCollectionClient
```suggestion
from crawlee.base_storage_client import BaseDatasetCollectionClient
```

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/key_value_store_client.py
> +from crawlee.base_storage_client.base_key_value_store_client import BaseKeyValueStoreClient
```suggestion
from crawlee.base_storage_client import BaseKeyValueStoreClient
```

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/key_value_store_collection_client.py
> +from crawlee.base_storage_client.base_key_value_store_collection_client import BaseKeyValueStoreCollectionClient
```suggestion
from crawlee.base_storage_client import BaseKeyValueStoreCollectionClient
```

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/request_queue_client.py
> +from crawlee.base_storage_client.base_request_queue_client import BaseRequestQueueClient
```suggestion
from crawlee.base_storage_client import BaseRequestQueueClient
```

2024-08-22 15:45 UTC, vdusek commented on src/apify/apify_storage_client/request_queue_collection_client.py
> +from crawlee.base_storage_client.base_request_queue_collection_client import BaseRequestQueueCollectionClient
```suggestion
from crawlee.base_storage_client import BaseRequestQueueCollectionClient
```

2024-08-22 15:50 UTC, vdusek commented on src/apify/event_manager.py
maybe call the module `platform_event_manager`? since we have `local_event_manager` in Crawlee

2024-08-26 12:56 UTC, janbuchar commented on src/apify/config.py
> +from crawlee._utils.models import timedelta_ms
There's more utilities that we use in the SDK, such as `generate_unique_resource_name`... I think that grabbing something private SDK is the lesser evil.

2024-08-26 15:38 UTC, janbuchar commented on src/apify/proxy_configuration.py
>  COUNTRY_CODE_REGEX = re.compile(r'^[A-Z]{2}$')
The module is now private, so I'm leaving those this way.

2024-08-27 14:05 UTC, vdusek requested changes
Last details...

2024-08-27 14:05 UTC, vdusek commented on src/apify/_utils.py
>  logger = getLogger(__name__)
It seems like these lines can be removed as well.

2024-08-27 14:12 UTC, janbuchar commented on src/apify/storages/__init__.py
> +from crawlee.storages import Dataset, KeyValueStore, RequestQueue
Apparently, the old SDK didn't have it either. So... no, I guess.

2024-08-27 14:43 UTC, vdusek approved these changes
LGTM :rocket:

2024-08-27 14:46 UTC, janbuchar commented
![image](https://github.com/user-attachments/assets/966703d1-9553-435b-8bf5-497f9c2e4543)

2024-08-27 15:05 UTC, merged